channels: 
  - conda-forge 
  - defaults 
dependencies: 
  - mpfr=4.1.0 
  - xz=5.4.6 
  - liblapack=3.9.0 
  - pylint=3.3.5 
  - importlib_resources=6.5.2 
  - nomkl=1.0 
  - freetype=2.10.4 
  - libsodium=1.0.18 
  - astroid=3.3.8 
  - hyperframe=6.1.0 
  - decorator=5.1.1 
  - brotli-python=1.0.9 
  - mpc=1.2.1 
  - libgcc-ng=11.2.0 
  - jupyter_core=5.7.2 
  - pure_eval=0.2.2 
  - dask-core=2025.5.1 
  - pathspec=0.10.3 
  - zstd=1.5.6 
  - brotli=1.0.9 
  - libbrotlienc=1.0.9 
  - pysocks=1.7.1 
  - packaging=24.2 
  - dipy=1.5.0 
  - libtiff=4.5.1 
  - blas=1.1 
  - unicodedata2=14.0.0 
  - libopenblas=0.3.21 
  - snowballstemmer=2.2.0 
  - libaec=1.1.3 
  - ca-certificates=2025.6.15 
  - lzo=2.10 
  - tomlkit=0.13.2 
  - libgfortran=3.0.0 
  - python-dateutil=2.9.0post0 
  - libbrotlidec=1.0.9 
  - h2=4.2.0 
  - zfp=1.0.0 
  - importlib-metadata=7.0.1 
  - openblas=0.3.4 
  - expat=2.6.4 
  - libzopfli=1.0.3 
  - black=24.10.0 
  - libev=4.33 
  - traitlets=5.14.3 
  - statsmodels=0.13.2 
  - ld_impl_linux-64=2.40 
  - pickleshare=0.7.5 
  - colorama=0.4.6 
  - mpmath=1.3.0 
  - yaml=0.2.5 
  - libnghttp2=1.57.0 
  - python_abi=3.10 
  - numexpr=2.8.0 
  - giflib=5.2.2 
  - libprotobuf=4.25.3 
  - aom=3.6.0 
  - hpack=4.1.0 
  - pywavelets=1.3.0 
  - dav1d=1.2.1 
  - brunsli=0.1 
  - toolz=1.0.0 
  - stack_data=0.2.0 
  - jxrlib=1.1 
  - ptyprocess=0.7.0 
  - cytoolz=0.11.2 
  - zstandard=0.23.0 
  - lz4-c=1.9.4 
  - libdeflate=1.22 
  - pytables=3.10.1 
  - gmp=6.2.1 
  - nest-asyncio=1.6.0 
  - libstdcxx-ng=11.2.0 
  - _openmp_mutex=5.1 
  - wheel=0.45.1 
  - libpng=1.6.39 
  - snappy=1.2.1 
  - cached-property=1.5.2 
  - matplotlib-base=3.5.2 
  - tk=8.6.14 
  - libgfortran-ng=13.2.0 
  - pycodestyle=2.12.1 
  - jpeg=9e 
  - cycler=0.12.1 
  - libbrotlicommon=1.0.9 
  - h5py=3.6.0 
  - zeromq=4.3.5 
  - imageio=2.37.0 
  - openjpeg=2.5.2 
  - flake8=7.1.1 
  - libwebp-base=1.3.2 
  - backcall=0.2.0 
  - libedit=3.1.20230828 
  - mypy_extensions=1.0.0 
  - typing-extensions=4.12.2 
  - setuptools=75.8.0 
  - lerc=4.0.0 
  - patsy=1.0.1 
  - cloudpickle=3.1.1 
  - munch=4.0.0 
  - libgfortran5=13.2.0 
  - pytorch=2.3.0 
  - libblas=3.9.0 
  - zlib=1.2.13 
  - hdf5=1.12.1 
  - readline=8.2 
  - pydocstyle=6.3.0 
  - bzip2=1.0.8 
  - tornado=6.4.2 
  - sqlite=3.45.3 
  - krb5=1.20.1 
  - prompt_toolkit=3.0.43 
  - click=8.1.8 
  - certifi=2025.6.15 
  - zlib-ng=2.0.7 
  - locket=1.0.0 
  - libcurl=8.12.1 
  - pyflakes=3.2.0 
  - isort=6.0.1 
  - gmpy2=2.1.2 
  - nibabel=5.3.2 
  - libssh2=1.11.1 
  - _libgcc_mutex=0.1 
  - idna=3.10 
  - cached_property=1.5.2 
  - mccabe=0.7.0 
  - libffi=3.4.4 
  - py-cpuinfo=9.0.0 
  - jupyter_client=8.6.3 
  - cpython=3.10.18 
  - partd=1.4.2 
  - brotli-bin=1.0.9 
  - libcblas=3.9.0 
  - imagecodecs=2024.9.22 
  - openssl=3.0.16 
  - dill=0.3.8 
  - libuuid=1.41.5 
  - blosc=1.21.3 
  - ncurses=6.4 
  - typing_extensions=4.12.2 
  - scikit-image=0.19.2 
  - libabseil=20240116.2 
  - c-blosc2=2.12.0 
  - munkres=1.1.4 
  - libgomp=11.2.0 
  - python=3.10.16 
  - libavif=1.1.1 
  - zipp=3.21.0 
  - importlib_metadata=7.0.1 
  - pycparser=2.22 
  - c-ares=1.19.1 
  - tqdm=4.67.1 
  - tifffile=2024.12.12 
  - lcms2=2.16 
  - pillow=11.1.0 
  - charls=2.2.0 
  - cfitsio=3.470 
  - pip 
  - pip: 
    - nvidia-nccl-cu12==2.19.3 
    - tinycss2==1.4.0 
    - mdurl==0.1.2 
    - pytz==2025.1 
    - jedi==0.19.2 
    - pexpect==4.9.0 
    - fqdn==1.5.1 
    - nbformat==5.10.4 
    - aiosignal==1.3.2 
    - httptools==0.6.4 
    - webcolors==24.11.1 
    - fastapi==0.115.8 
    - async-lru==2.0.4 
    - nvidia-cusparse-cu12==12.1.0.106 
    - markdown==3.7 
    - json5==0.10.0 
    - pyjwt==2.10.1 
    - exceptiongroup==1.2.2 
    - pure-eval==0.2.3 
    - uri-template==1.3.0 
    - arrow==1.3.0 
    - kiwisolver==1.4.8 
    - pyyaml==6.0.2 
    - protobuf==4.23.4 
    - filelock==3.17.0 
    - uvicorn==0.34.0 
    - numpy==1.26.4 
    - argon2-cffi==23.1.0 
    - terminado==0.18.1 
    - multidict==6.1.0 
    - scikit-learn==1.3.2 
    - jupyter-server-terminals==0.5.3 
    - widgetsnbextension==4.0.13 
    - beautifulsoup4==4.13.3 
    - nvidia-cufft-cu12==11.0.2.54 
    - soupsieve==2.6 
    - markdown-it-py==3.0.0 
    - requests==2.32.3 
    - jupyterlab-widgets==3.0.13 
    - google-auth-oauthlib==1.2.1 
    - torchmetrics==1.3.1 
    - ipywidgets==8.1.1 
    - prometheus-client==0.21.1 
    - fire==0.7.0 
    - nvidia-cuda-nvrtc-cu12==12.1.105 
    - anyio==4.8.0 
    - litdata==0.2.32 
    - tensorboard==2.15.1 
    - simple-term-menu==1.6.6 
    - jupyter-events==0.12.0 
    - pyasn1-modules==0.4.1 
    - xgboost==2.0.2 
    - contourpy==1.3.1 
    - nvidia-nvjitlink-cu12==12.8.61 
    - tomli==2.2.1 
    - mistune==3.1.1 
    - requests-oauthlib==2.0.0 
    - platformdirs==4.3.6 
    - frozenlist==1.5.0 
    - nbconvert==7.16.6 
    - aiohttp==3.11.12 
    - httpcore==1.0.7 
    - rfc3986-validator==0.1.1 
    - webencodings==0.5.1 
    - executing==2.2.0 
    - async-timeout==5.0.1 
    - stack-data==0.6.3 
    - send2trash==1.8.3 
    - jsonpointer==3.0.0 
    - pygments==2.19.1 
    - docker==7.1.0 
    - tzdata==2025.1 
    - nvidia-cudnn-cu12==8.9.2.26 
    - lightning-sdk==0.1.55 
    - pyzmq==26.2.1 
    - fsspec==2025.2.0 
    - pandocfilters==1.5.1 
    - notebook-shim==0.2.4 
    - aiohappyeyeballs==2.4.4 
    - threadpoolctl==3.5.0 
    - nbclient==0.10.2 
    - s3transfer==0.11.2 
    - websocket-client==1.8.0 
    - bleach==6.2.0 
    - nvidia-curand-cu12==10.3.2.106 
    - sniffio==1.3.1 
    - markupsafe==3.0.2 
    - python-dotenv==1.0.1 
    - jmespath==1.0.1 
    - defusedxml==0.7.1 
    - jupyterlab-server==2.27.3 
    - grpcio==1.70.0 
    - torch==2.2.1+cu121 torchvision==0.17.1+cu121 torchaudio==2.2.1 --index-url https://download.pytorch.org/whl/cu121
    - ipython==8.17.2 
    - prompt-toolkit==3.0.50 
    - fonttools==4.55.8 
    - nvidia-cuda-cupti-cu12==12.1.105 
    - annotated-types==0.7.0 
    - lightning-utilities==0.12.0 
    - overrides==7.7.0 
    - tensorboard-data-server==0.7.2 
    - rsa==4.9 
    - jupyter-lsp==2.2.5 
    - pyasn1==0.6.1 
    - yarl==1.18.3 
    - comm==0.2.2 
    - nvidia-nvtx-cu12==12.1.105 
    - matplotlib==3.8.2 
    - rfc3339-validator==0.1.4 
    - jupyterlab-pygments==0.3.0 
    - triton==2.2.0 
    - h11==0.14.0 
    - rich==13.9.4 
    - python-multipart==0.0.20 
    - watchfiles==1.0.4 
    - attrs==25.1.0 
    - starlette==0.45.3 
    - scipy==1.11.4 
    - jsonschema==4.23.0 
    - pydantic-core==2.27.2 
    - charset-normalizer==3.4.1 
    - botocore==1.36.14 
    - types-python-dateutil==2.9.0.20241206 
    - nvidia-cuda-runtime-cu12==12.1.105 
    - lightning-cloud==0.5.70 
    - pytorch-lightning==2.5.0.post0 
    - jinja2==3.1.5 
    - google-auth==2.38.0 
    - parso==0.8.4 
    - networkx==3.4.2 
    - absl-py==2.1.0 
    - httpx==0.28.1 
    - websockets==14.2 
    - boto3==1.36.14 
    - nvidia-cusolver-cu12==11.4.5.107 
    - litserve==0.2.6 
    - pyparsing==3.2.1 
    - joblib==1.4.2 
    - debugpy==1.8.12 
    - psutil==6.1.1 
    - urllib3==2.3.0 
    - asttokens==3.0.0 
    - lightning==2.5.0.post0 
    - ipykernel==6.26.0 
    - propcache==0.2.1 
    - uvloop==0.21.0 
    - fastjsonschema==2.21.1 
    - nvidia-cublas-cu12==12.1.3.1 
    - argon2-cffi-bindings==21.2.0 
    - pandas==2.1.4 
    - termcolor==2.5.0 
    - rpds-py==0.22.3 
    - jupyter-server==2.15.0 
    - werkzeug==3.1.3 
    - backoff==2.2.1 
    - oauthlib==3.2.2 
    - matplotlib-inline==0.1.7 
    - referencing==0.36.2 
    - jupyterlab==4.2.0 
    - torchvision==0.17.1+cu121 
    - isoduration==20.11.0 
    - python-json-logger==3.2.1 
    - wcwidth==0.2.13 
    - babel==2.17.0 
    - sympy==1.13.3 
    - six==1.17.0 
    - jsonschema-specifications==2024.10.1 
    - pydantic==2.10.6 
    - cffi==1.17.1 
    - cachetools==5.5.1 
