dbrain:
  train:
    num_epochs: 1000
    device: cuda
    mask_p: 0.3
    dropout_p: 0.3
    learning_rate: 0.0001
    batch_size: 8
    use_scheduler: False
    scheduler_step_size: 1000
    scheduler_gamma: 0.1
    checkpoint_dir: "mds2s/checkpoints/dbrain"
  reconstruct:
    n_preds: 5
    mask_p: 0.3
    device: cuda
    metrics_dir: "mds2s/metrics/dbrain"
    images_dir: "mds2s/images/dbrain"
  model:
    in_channel: 10 # is the same as the number of volumes
    out_channel: 10
  data:
    num_b0s: 6
    num_volumes: 10
    noise_sigma: 0.1
    bvalue: 2500
    nii_path_lightning: "/teamspace/s3_folders/dwmri-dataset/D_BRAIN_b2500_6_60_14_HCP_nless.nii"
    bvecs_path_lightning: "/teamspace/s3_folders/dwmri-dataset/D_BRAIN_b2500_6_60_HCP_b_matrix.txt"
    nii_path: "/home/paco/d_brain/D_BRAIN_b2500_6_60_14_HCP_nless.nii"
    bvecs_path: "/home/paco/d_brain/D_BRAIN_b2500_6_60_HCP_b_matrix.txt"
stanford:
  train:
    num_epochs: 100
    num_volumes: 6
    device: cpu
    mask_p: 0.3
    dropout_p: 0.3
    checkpoint_dir: "checkpoints"
    learning_rate: 0.00001
    batch_size: 8
  model:
    in_channel: 9
    out_channel: 9
  data:
    num_volumes: 10
    noise_sigma: 0.01
    bvalue: 2500
