dbrain:
  train:
    num_epochs: 60
    device: cuda
    learning_rate: 0.001
    batch_size: 32
    use_scheduler: True
    scheduler_type: "reduceLROnPlateau"
    checkpoint_dir: "drcnet/checkpoints/dbrain"
    ## cosine annealing warm restarts
    scheduler_T_0: 30
    eta_min_lr: 0.0001
    scheduler_T_mult: 2
    ## stepLR
    scheduler_step_size: 40
    scheduler_gamma: 0.1
    ## reduceLROnPlateau
    scheduler_patience: 10
    scheduler_factor: 0.1
    min_lr: 0.00001
  reconstruct:
    device: cuda
    metrics_dir: "drcnet/metrics/dbrain"
    images_dir: "drcnet/images/dbrain"
  model:
    in_channel: 9 # is the number of volumes taking one out to be predicted
    out_channel: 1 # is the predicted volume
    groups: 1
    dense_convs: 2
    residual: true
    base_filters: 32
  data:
    patch_size: 16
    step: 4
    num_b0s: 6
    num_volumes: 10
    noise_sigma: 0.1
    bvalue: 2500
    take_x: 128
    take_y: 128
    take_z: 96
    nii_path_lightning: "/teamspace/s3_folders/dwmri-dataset/D_BRAIN_b2500_6_60_14_HCP_nless.nii"
    bvecs_path_lightning: "/teamspace/s3_folders/dwmri-dataset/D_BRAIN_b2500_6_60_HCP_b_matrix.txt"
    nii_path: "/home/paco/d_brain/D_BRAIN_b2500_6_60_14_HCP_nless.nii"
    bvecs_path: "/home/paco/d_brain/D_BRAIN_b2500_6_60_HCP_b_matrix.txt"
stanford:
  train:
    num_epochs: 100
    num_volumes: 6
    device: cpu
    mask_p: 0.3
    dropout_p: 0.3
    checkpoint_dir: "checkpoints"
    learning_rate: 0.00001
    batch_size: 8
  model:
    in_channel: 9
    out_channel: 9
  data:
    num_volumes: 10
    noise_sigma: 0.01
    bvalue: 2500
